# Deep Learning 3

Importing GDrive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Importing Images

Reading an image from GDrive and turning it into numpy array, then converting it into a Pytorch tensor

In [6]:
#importing image

import imageio
import torch

img_arr = imageio.imread('/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/dogge.jpg')

img_arr.shape
img = torch.from_numpy(img_arr)
batch_size = 4
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

<ipython-input-6-1c68cc003044>:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/dogge.jpg')


Importing a set of images from GDrive folder and converting them into numpy arrays, then converting them into Pytorch tensor

In [4]:
#importing batch of images

import os

data_dir = '/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/images'
filenames = [name for name in os.listdir(data_dir)
if os.path.splitext(name)[-1] == '.jpg']

for i, filename in enumerate(filenames):
  img_arr = imageio.imread(os.path.join(data_dir, filename))
  img_t = torch.from_numpy(img_arr)
  img_t = img_t.permute(2, 0, 1)
  img_t = img_t[:3]
  batch[i] = img_t

batch

<ipython-input-4-1b2b95a17779>:10: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


tensor([[[[ 98,  99,  99,  ...,  44,  70, 116],
          [ 51,  52,  52,  ...,  54,  85, 105],
          [ 41,  42,  41,  ...,  59, 107, 121],
          ...,
          [  8,   8,   8,  ...,  13,  13,  13],
          [  8,   8,   8,  ...,  13,  13,  13],
          [  9,   8,   8,  ...,  13,  13,  13]],

         [[ 96,  97,  97,  ...,  32,  62, 110],
          [ 50,  51,  51,  ...,  42,  77,  99],
          [ 45,  46,  45,  ...,  47,  99, 115],
          ...,
          [ 21,  21,  21,  ...,  17,  17,  17],
          [ 21,  21,  21,  ...,  17,  17,  17],
          [ 22,  21,  21,  ...,  17,  17,  17]],

         [[ 75,  76,  76,  ...,  44,  73, 122],
          [ 32,  33,  33,  ...,  52,  88, 111],
          [ 31,  32,  31,  ...,  57, 110, 125],
          ...,
          [ 27,  27,  27,  ...,  18,  18,  18],
          [ 29,  29,  29,  ...,  18,  18,  18],
          [ 30,  29,  29,  ...,  18,  18,  18]]],


        [[[108, 103,  98,  ...,  26,  25,  31],
          [105, 102,  98,  ...,  35

In [5]:
#Normalizing images

batch = batch.float()
batch /= 255.0

batch

tensor([[[[0.3843, 0.3882, 0.3882,  ..., 0.1725, 0.2745, 0.4549],
          [0.2000, 0.2039, 0.2039,  ..., 0.2118, 0.3333, 0.4118],
          [0.1608, 0.1647, 0.1608,  ..., 0.2314, 0.4196, 0.4745],
          ...,
          [0.0314, 0.0314, 0.0314,  ..., 0.0510, 0.0510, 0.0510],
          [0.0314, 0.0314, 0.0314,  ..., 0.0510, 0.0510, 0.0510],
          [0.0353, 0.0314, 0.0314,  ..., 0.0510, 0.0510, 0.0510]],

         [[0.3765, 0.3804, 0.3804,  ..., 0.1255, 0.2431, 0.4314],
          [0.1961, 0.2000, 0.2000,  ..., 0.1647, 0.3020, 0.3882],
          [0.1765, 0.1804, 0.1765,  ..., 0.1843, 0.3882, 0.4510],
          ...,
          [0.0824, 0.0824, 0.0824,  ..., 0.0667, 0.0667, 0.0667],
          [0.0824, 0.0824, 0.0824,  ..., 0.0667, 0.0667, 0.0667],
          [0.0863, 0.0824, 0.0824,  ..., 0.0667, 0.0667, 0.0667]],

         [[0.2941, 0.2980, 0.2980,  ..., 0.1725, 0.2863, 0.4784],
          [0.1255, 0.1294, 0.1294,  ..., 0.2039, 0.3451, 0.4353],
          [0.1216, 0.1255, 0.1216,  ..., 0

In [6]:
# Normalizing based on the mean and standart deviation of a data set

n_channels = batch.shape[1]
for c in range (n_channels):
  mean = torch.mean(batch[:, c])
  std = torch.std(batch[:, c])
  batch[:, c] = (batch[:, c] - mean) / std
batch

tensor([[[[-0.0227, -0.0085, -0.0085,  ..., -0.7859, -0.4184,  0.2317],
          [-0.6870, -0.6729, -0.6729,  ..., -0.6446, -0.2064,  0.0763],
          [-0.8283, -0.8142, -0.8283,  ..., -0.5739,  0.1045,  0.3024],
          ...,
          [-1.2948, -1.2948, -1.2948,  ..., -1.2241, -1.2241, -1.2241],
          [-1.2948, -1.2948, -1.2948,  ..., -1.2241, -1.2241, -1.2241],
          [-1.2807, -1.2948, -1.2948,  ..., -1.2241, -1.2241, -1.2241]],

         [[ 0.1762,  0.1905,  0.1905,  ..., -0.7432, -0.3123,  0.3773],
          [-0.4847, -0.4703, -0.4703,  ..., -0.5996, -0.0968,  0.2193],
          [-0.5565, -0.5421, -0.5565,  ..., -0.5278,  0.2193,  0.4491],
          ...,
          [-0.9013, -0.9013, -0.9013,  ..., -0.9587, -0.9587, -0.9587],
          [-0.9013, -0.9013, -0.9013,  ..., -0.9587, -0.9587, -0.9587],
          [-0.8869, -0.9013, -0.9013,  ..., -0.9587, -0.9587, -0.9587]],

         [[-0.1176, -0.1034, -0.1034,  ..., -0.5581, -0.1460,  0.5502],
          [-0.7286, -0.7144, -

In [7]:
#Building a 3d tensor with stacked images

dir_path = "/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/di_com"
vol_arr = imageio.volread(dir_path, 'DICOM')

vol_arr.shape

Reading DICOM (examining files): 1/99 files (1.0%)2/99 files (2.0%)3/99 files (3.0%)4/99 files (4.0%)5/99 files (5.1%)7/99 files (7.1%)8/99 files (8.1%)9/99 files (9.1%)10/99 files (10.1%)11/99 files (11.1%)12/99 files (12.1%)13/99 files (13.1%)14/99 files (14.1%)15/99 files (15.2%)16/99 files (16.2%)17/99 files (17.2%)18/99 files (18.2%)19/99 files (19.2%)20/99 files (20.2%)21/99 files (21.2%)22/99 files (22.2%)23/99 files (23.2%)24/99 files (24.2%)25/99 files (25.3%)26/99 files (26.3%)27/99 files (27.3%)28/99 files

(99, 512, 512)

In [25]:
vol = torch.from_numpy(vol_arr).float()
vol = torch.unsqueeze(vol, 0)

vol.shape

torch.Size([1, 99, 512, 512])

In [3]:
#turning CSV file data into tensor

import csv
import numpy as np

wine_path = "/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/5_XLS.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)

wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [4]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))

wineq_numpy.shape, col_list


((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [7]:
wineq = torch.from_numpy(wineq_numpy)

wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [8]:
# removing columns

data = wineq[:, :-1]

data, data.shape


(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [9]:
target = wineq[:, -1]

target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

In [10]:
target = wineq[:, -1].long()

target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [11]:
# one-hot encoding

target_onehot = torch.zeros(target.shape[0], 10)
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

target_onehot

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [12]:
target_unsqeezed = target.unsqueeze(1)
target_unsqeezed

tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])

In [14]:
data_mean = torch.mean(data, dim=0)
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [15]:
data_var = torch.var(data, dim=0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [16]:
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

In [18]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()


(torch.Size([4898]), torch.bool, tensor(20))

In [20]:
bad_data = data[bad_indexes]
bad_data.shape, bad_data[0]

(torch.Size([20, 11]),
 tensor([8.5000e+00, 2.6000e-01, 2.1000e-01, 1.6200e+01, 7.4000e-02, 4.1000e+01,
         1.9700e+02, 9.9800e-01, 3.0200e+00, 5.0000e-01, 9.8000e+00]))

In [21]:
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)]
good_data = data[target >= 7]

bad_data, mid_data, good_data

(tensor([[8.5000e+00, 2.6000e-01, 2.1000e-01, 1.6200e+01, 7.4000e-02, 4.1000e+01,
          1.9700e+02, 9.9800e-01, 3.0200e+00, 5.0000e-01, 9.8000e+00],
         [5.8000e+00, 2.4000e-01, 4.4000e-01, 3.5000e+00, 2.9000e-02, 5.0000e+00,
          1.0900e+02, 9.9130e-01, 3.5300e+00, 4.3000e-01, 1.1700e+01],
         [9.1000e+00, 5.9000e-01, 3.8000e-01, 1.6000e+00, 6.6000e-02, 3.4000e+01,
          1.8200e+02, 9.9680e-01, 3.2300e+00, 3.8000e-01, 8.5000e+00],
         [7.1000e+00, 3.2000e-01, 3.2000e-01, 1.1000e+01, 3.8000e-02, 1.6000e+01,
          6.6000e+01, 9.9370e-01, 3.2400e+00, 4.0000e-01, 1.1500e+01],
         [6.9000e+00, 3.9000e-01, 4.0000e-01, 4.6000e+00, 2.2000e-02, 5.0000e+00,
          1.9000e+01, 9.9150e-01, 3.3100e+00, 3.7000e-01, 1.2600e+01],
         [1.0300e+01, 1.7000e-01, 4.7000e-01, 1.4000e+00, 3.7000e-02, 5.0000e+00,
          3.3000e+01, 9.9390e-01, 2.8900e+00, 2.8000e-01, 9.6000e+00],
         [7.9000e+00, 6.4000e-01, 4.6000e-01, 1.0600e+01, 2.4400e-01, 3.3000e+01,


In [23]:
bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

bad_mean, mid_mean, good_mean
bad_mean.shape

torch.Size([11])

In [28]:
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
  print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))


 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


In [29]:
total_sulfur_threshold = 141.83
total_sulfur_data = data[:,6]
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_threshold)

predicted_indexes.shape, predicted_indexes.dtype, predicted_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(2727))

In [30]:
actual_indexes = target > 5

actual_indexes.shape, actual_indexes.dtype, actual_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(3258))

In [31]:
n_matches = torch.sum(actual_indexes & predicted_indexes).item()
n_predicted = torch.sum(predicted_indexes).item()
n_actual = torch.sum(actual_indexes).item()

n_matches, n_matches / n_predicted, n_matches / n_actual

(2018, 0.74000733406674, 0.6193984039287906)

In [32]:
bikes_numpy = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/hour.csv", dtype=np.float32, delimiter=",", skiprows=1, converters={1: lambda x: float(x[8:10])})

bikes = torch.from_numpy(bikes_numpy)
bikes

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00, 1.3000e+01,
         1.6000e+01],
        [2.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 8.0000e+00, 3.2000e+01,
         4.0000e+01],
        [3.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 5.0000e+00, 2.7000e+01,
         3.2000e+01],
        ...,
        [1.7377e+04, 3.1000e+01, 1.0000e+00,  ..., 7.0000e+00, 8.3000e+01,
         9.0000e+01],
        [1.7378e+04, 3.1000e+01, 1.0000e+00,  ..., 1.3000e+01, 4.8000e+01,
         6.1000e+01],
        [1.7379e+04, 3.1000e+01, 1.0000e+00,  ..., 1.2000e+01, 3.7000e+01,
         4.9000e+01]])

In [39]:
bikes.shape, bikes.stride()

(torch.Size([17379, 17]), (17, 1))

In [52]:
bikes.shape[1]

17

In [57]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])

daily_bikes.shape, daily_bikes.stride()

RuntimeError: ignored

In [41]:
daily_bikes = daily_bikes.transpose(1, 2)

daily_bikes.shape, daily_bikes.stride()

NameError: ignored

In [ ]:
first_day = bikes[:24].long()
weather_onehot = torch.zeros(first_day.shape[0], 4)
first_day[:,9]
weather_onehot.scatter_(dim=1, index=first_day[:,9].unsqueeze(1).long() - 1, value=1.0)
torch.cat((bikes[:24], weather_onehot), 1)[:1]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,  6.0000,
          0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,  3.0000, 13.0000,
         16.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [ ]:
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4, daily_bikes.shape[2])
daily_weather_onehot.shape

daily_weather_onehot.scatter_(1, daily_bikes[:,9,:].long().unsqueeze(1) - 1, 1.0)
daily_weather_onehot.shape
daily_bikes = torch.cat((daily_bikes, daily_weather))

NameError: ignored

In [ ]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)

temp = daily_bikes[:, 10, :]
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - torch.mean(temp)) / torch.std(temp))

# Working with text

In [59]:
with open('/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/text.txt', encoding='utf8') as f: text = f.read()

lines = text.split('\n')
line = lines[200]
line

letter_t = torch.zeros(len(line), 128)

letter_t.shape

torch.Size([25, 128])

In [60]:
for i, letter in enumerate(line.lower().strip()):
  letter_index = ord(letter) if ord(letter) < 128 else 0
  letter_t[i][letter_index] = i

In [61]:
def clean_words(input_str):
  punctuation = '.,;:"!?“”_-'
  word_list = input_str.lower().replace('\n', ' ').split()
  word_list = [word.strip(punctuation) for word in word_list]
  return word_list

words_in_line = clean_words(line)
line, words_in_line

('      “What is his name?”', ['what', 'is', 'his', 'name'])

In [62]:
word_list = sorted(set(clean_words(text)))
word2index_dict = {word: i for (i, word) in enumerate(word_list)}

len(word2index_dict), word2index_dict['impossible']

(7264, 3372)

In [63]:
word_t = torch.zeros(len(words_in_line), len(word2index_dict))

for i, word in enumerate(words_in_line):
  word_index = word2index_dict[word]
  word_t[i][word_index] = 1
  print('{:2} {:4} {}'.format(i, word_index, word))
print(word_t.shape)

 0 7049 what
 1 3669 is
 2 3211 his
 3 4302 name
torch.Size([4, 7264])


# Working with audio

In [64]:
import scipy.io.wavfile as wavfile
freq, waveform_arr = wavfile.read('/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/wake_up.wav')

freq, waveform_arr

<ipython-input-64-3ef693df6621>:2: WavFileWarning: Chunk (non-data) not understood, skipping it.
  freq, waveform_arr = wavfile.read('/content/drive/MyDrive/Colab Notebooks/DeepLearning/data/wake_up.wav')


(44100,
 array([[ 0,  0],
        [-1,  0],
        [ 3,  0],
        ...,
        [-2,  4],
        [ 2, -3],
        [-2,  2]], dtype=int16))

In [65]:
waveform = torch.from_numpy(waveform_arr).float()

waveform.shape

torch.Size([1856271, 2])

In [67]:
from scipy import signal

f_arr, t_arr, sp_arr = signal.spectrogram(waveform_arr, freq)
sp_mono = torch.from_numpy(sp_arr)
sp_mono.shape

/usr/local/lib/python3.9/dist-packages/scipy/signal/_spectral_py.py:2014: UserWarning: nperseg = 256 is greater than input length  = 2, using nperseg = 2
  warnings.warn('nperseg = {0:d} is greater than input length '


torch.Size([1856271, 2, 1])

In [68]:
sp_left = sp_right = sp_arr
sp_left_t = torch.from_numpy(sp_left)
sp_right_t = torch.from_numpy(sp_right)

sp_left_t.shape, sp_right_t.shape

(torch.Size([1856271, 2, 1]), torch.Size([1856271, 2, 1]))

In [69]:
sp_t = torch.stack((sp_left_t, sp_right_t), dim = 0)
sp_t.shape

torch.Size([2, 1856271, 2, 1])

# Working with videos

In [ ]:
import imageio


reader = imageio.get_reader('./drive/MyDrive/2020-06-19 16-56-39.mp4')
meta = reader.get_meta_data()
n_frames = reader.count_frames()
n_channels = 3
n_meta =(meta['size'])
video = torch.empty(n_channels, n_frames, *n_meta)
video.shape

for i, frame_arr in enumerate(reader):
  frame = torch.from_numpy(frame_arr).float()
  video[:,i]=torch.transpose(frame,0,2)